language: android
jdk: oraclejdk8
android:
  components:
    - platform-tools
    - tools
    - build-tools-23.0.3
    - android-23
  licenses:
    - '.+'
script: 
  - export VERBOSE=1
  - export USE_GRADLE_WRAPPER=0
  - ./build.sh
  - ./build_test_app.sh
