language: android
jdk: openjdk7
android:
  components:
    - platform-tools
    - tools
    - build-tools-23.0.1
    - android-23
  licenses:
    - '.+'
script:
  - ./build.sh
  - gradle installArchives
