language: android
jdk: oraclejdk8
android:
  components:
    - platform-tools
    - tools
    - build-tools-23.0.1
    - android-23
  licenses:
    - '.+'
install: ./build.sh
script: gradle installArchives
